Data storage accses
GeorgeKuzora/tg_bot_job_search pull request #10
Opened 2023-05-15 07:36 UTC by ErmolaevaOlga

2023-05-15 15:11 UTC, GeorgeKuzora requested changes
Нужно обсудить стратегию сохранения ещё раз. Наверное ее визуализировать вначале. Чтобы всем было понятно. Я постараюсь это сделать.

Посмотри на замечания по тексту. Там есть что поправить.

В следующий раз тесты лучше отдельным пулл реквестом засылать. Они ведь не относятся к сохранению файлов

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +PATH = os.getcwd () +"\src\data_storage\data\\"
Не в ту сторону слэши :)

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +    def __init__(self, name, company, solary, link) -> None:
salary

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +def check_data(PATH: str) -> bool:
Лучше вынести создание папки в другую функцию. А эту переименовать функцию в что то вроде check_path_exists.

Само название говорит нам что мы проверяем что путь существует. Но оно не сообщает что мы ещё и собираемся создать папку в системе. Плюс если будут проблемы с сообщением папки то легче их исправить в отдельной функции.

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +def create_json_str(new_vacancy) -> str:
Зачем отдельно сдавать строки? Библиотека json сама может преобразовать типы данных в подходящие типы json.
JSON

https://docs.python.org/3/library/json.html#encoders-and-decoders

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +def read_list_vacancy(list_company: list):
Задать лучше подумать над тем, чтобы сформировать список словарей. А в другой функции его записать в json файл.

Плюс название функции прямо противоположно тому что она выполняет. Функция называется read... А в итоге она делает write.

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +def create_vacancy_from_tuple(vacancy_data: tuple) -> str:
Может сразу формировать словарь Для записи в json?

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +        jsonfile.closed
При использовании with это не нужно. Менеджер контекста сам позаботиться чтобы закрыть файл.

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +            save_json_in_file(json_str)
Здесь очень много раз придётся открывать и закрывать файлы.

2023-05-15 15:11 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +        return True
Не нужно если убрать else а `return true` вынести из под if

2023-05-16 01:28 UTC, ErmolaevaOlga commented on src/data_storage/data_storage_accses.py
> +    def __init__(self, name, company, solary, link) -> None:
Испанский стыд)

2023-05-16 01:30 UTC, ErmolaevaOlga commented on src/data_storage/data_storage_accses.py
> +def create_json_str(new_vacancy) -> str:
Я это сделала на случай внесения изменений в записываемые данные, например объединения информации с тем что от тг бота приходит. Если в одном кортеже будем хранить данные и о вакансии и о пользователе

2023-05-16 01:31 UTC, ErmolaevaOlga commented on src/data_storage/data_storage_accses.py
> +        jsonfile.closed
Поняла, прочитала где то что он конечно закрывает, но хорошим тоном является прописать закрыть файл в ручную

2023-05-16 13:33 UTC, GeorgeKuzora requested changes

2023-05-16 13:33 UTC, GeorgeKuzora commented on src/data_storage/data_storage_accses.py
> +    return getattr(new_user, "user_id") + "_" + getattr(new_user, "region") + "_" +getattr(new_user, "keyword") + " " + now[:10]
Файл должен иметь название в виде id пользователя, без дополнительных данных.

2023-05-17 04:58 UTC, GeorgeKuzora approved these changes

2023-05-17 05:01 UTC, merged