Added the site scraper block https://career.habr.com
GeorgeKuzora/tg_bot_job_search pull request #2
Opened 2023-04-19 10:24 UTC by ErmolaevaOlga

Работа блока парсинга:
1) Получаем  данные от пользователя (принято JOB - ключевое слово для поиска, CURRENT_REGION - геолокация, пока формируется из словаря с 2 городами, дальше  нужно будет либо расширить словарь и организовать по нему поиск, либо подключиться к апи геобазы которую использует хабр)
2) В функции get_useragent() формируется фейковый заголовок для того чтобы обойти защиту от парсинга . 
3) Создается запрос в функции  make_response() с аргументами - url (формируется в функции make_link_career() с использованием полученных от пользователя данных и счетчиком страниц равным1) и фейковым заголовком
4) Далее проверяется ответ страницы на запрос в функции check_connection()
5)  Получив ответ от сайта, формируется суп в функции create_beautiful_soup()
6) find_vacancy_card() - составление списка ссылок на первой странице методом поиск в полученном супе ссылок на карточки вакансий
7)  Циклом перебираются все страницы сайта (добавлением в счетчик страниц 1) пока в ответ на поиск карточек вакансий не придет None, с добавлением всех ссылок в один результирующий список - в функции get_links()
8) Перебираем все ссылки из созданного списка и сохраняем данные по вакансии в кортеж. Функция get_company() записывает из карточки вакансии название вакансии, название компании, зарплата (она не указана во всех карточках, поэтому реализован блок try - если нет зарплаты - сохраняется пустое значение) и сама ссылка на вакансию. В функции get_list_company() в цикле все кортежи о вакансиях соединяются в список
9) Результат выводится в консоль. 

Сделала наброски сохранения в json если это будет необходимо. Но вакансии меняются очень быстро, не уверена что есть необходимость их сохранения, возможно их надо постоянно парсить и выводить пользователю в процессе работы бота

2023-04-19 14:53 UTC, GeorgeKuzora requested changes
Оставил комментарии по коду. Нужно подумать как исправить их. Особенно с блоком try-except.

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +def make_response(current_url: str):
Нужно добавить возвращаемый тип.

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +        return
Нужно вернуть пустой лист или link_list. Нужно стараться не возвращать None.

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +    if check_connection(response) != True:
Лучше заменить на == False

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +    """Создает запрос к списку вакансий"""
Скорее к веб-странице я думаю

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +        return
Не нужно возвращать None. В этом случае лучше вызвать исключение и не передавать пустое значение в компилятор.

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +           if find_vacancy_card(response) != None:
Лучше поставить вместо None False

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +    while find_vacancy_card(response) != None:
Лучше поставить вместо None False

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +        time.sleep(1)
Действительно ли нужно?

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +            print("На этом месте будет обработка ошибок")
В таких случаях лучше pass и комментарий

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +        return
None лучше не возвращать

2023-04-19 14:53 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +    try:
Неправильно использовать в этом случае try-except. Except сработает только в случае ошибки. При правильной работе except не будет запущен.

2023-04-19 15:48 UTC, ErmolaevaOlga commented on src/parsers/parser_habr.py
> +        time.sleep(1)
Читала что без слипов в этом процессе можно перегрузить сервер

2023-04-19 15:53 UTC, ErmolaevaOlga commented on src/parsers/parser_habr.py
> +    try:
Я первый раз пользовалась этим блоком, не поняла почему не правильно. Мы же  ждем что найдем такой  атрибут и если не нашли возвращаем пустое значение. Просто не знаю как описать поиск элемента на странице, если не использовать None и try

2023-04-19 15:54 UTC, ErmolaevaOlga commented on src/parsers/parser_habr.py
> +def make_response(current_url: str):
Я пока так и не поняла какой тип возвращает запрос, завтра type воспользуюсь

2023-04-20 05:04 UTC, GeorgeKuzora commented on src/parsers/parser_habr.py
> +    try:
Можно как то так. soup.find вернет None если не найдет значение. Поэтому в этом случае заменим salary на пустую строку.

```python
def get_company(link: str) -> tuple:
    """Создание кортежа данных по вакансии"""
    response = make_response(link)
    if not check_connection(response):
        return ()
    soup = create_beautiful_soup(response)
    salary = soup.find('div', attrs={"class":"basic-salary basic-salary--appearance-vacancy-header"}).text
    if not salary:
         salary = ""
    tuple_job =(
                   soup.find('h1', attrs={"class":"page-title__title"}).text,
                   soup.find('div', attrs={"class":"company_name"}).text,
                   salary,
                   #CURRENT_REGION, - здесь будет прописан регион поиска, вводимый пользователем
                   link
    )
    return tuple_job
```

Так как soup.find не вызывает ошибку если не найдет элемент, то метод с try-except с ним работать не будет. код в except вызывается только в том случае если в блоке под try возникла ошибка.

2023-04-26 03:35 UTC, ErmolaevaOlga commented on src/parsers/parser_habr.py
> +    try:
Так не работает, он ищет заголовок и обращается к его атрибуту - тексту, но когда заголовка нет получается возвращается ошибка 'NoneType' object has no attribute 'text'. Но я использовала ту же логику немного с другим кодом 


```python
if not soup.find('div', attrs={"class":"basic-salary basic-salary--appearance-vacancy-header"}):
         salary = ""
    else:
        salary = soup.find('div', attrs={"class":"basic-salary basic-salary--appearance-vacancy-header"}).text

```

2023-04-27 15:06 UTC, GeorgeKuzora approved these changes
Хорошо

2023-04-27 18:04 UTC, merged