Add Parser trudvsem.ru
GeorgeKuzora/tg_bot_job_search pull request #4
Opened 2023-04-26 14:05 UTC by Kustovweb

Описание парсера:
1. Получаем данные от пользователя в виде кортежа, в функции create_link() выполняем деструктуризацию кортежа -> region (регион) и base_vacancy (вакансия), и формирует ссылку с необходимыми параметрами
2. В файле list_region имеется словарь регионов, а также функция get_region_code() возвращающая код региона (необходимо улучшить шаблон поиска)
3. check_connection() проверяет соединение
4. make_response() формирует get запрос используется в search_vacancy()
5. search_vacancy() функция поиска вакансий, в цикле формирует список кортежей.

2023-04-30 12:06 UTC, LushnikovSR commented on src/parsers/list_region.py
> +    """Функция возвращающая код региона"""
С этой функцией будет проблема когда человек введет Санкт-Петербург или другой город не совпадающей с названием области, поэтому нужно либо добавить в этот словарь соответствующие исключения хотя бы самые крупные города, либо предусмотреть соответствующую функцию.

2023-04-30 12:28 UTC, LushnikovSR commented on src/parsers/scraper_trud_vsem.py
> +def check_connection(response: Any) -> bool:
В аннотации вместо "Any" лучше поставить "requests.Response"

2023-04-30 12:28 UTC, LushnikovSR commented on src/parsers/scraper_trud_vsem.py
> +def make_response(url: str) -> Any:
Эту функцию нужно связать с функцией check_connection(), ее можно использовать в качестве декоратора.

2023-04-30 12:35 UTC, LushnikovSR commented on src/parsers/scraper_trud_vsem.py
> +        return [False]
На данный момент договорились возвращать пустые списки, поэтому False лучше убрать.

2023-04-30 12:38 UTC, LushnikovSR commented on src/parsers/scraper_trud_vsem.py
> +print(search_vacancy(create_link(BASE_URL, ("Frontend", "Москва"))))
Принт здесь нужно убрать добавить if __name__ == "__main__" и методы main() и get_vacancys_data(keyward: str, region: str) -> list: запускающий код

2023-04-30 12:42 UTC, LushnikovSR reviewed
Для удобства отладки стоит добавить несколько exception raise. Также Георгий просил чтобы мы сделали папки с unit-тестами для своих модулей, хотя я и сам unit-тесты еще не сделал.

2023-04-30 13:58 UTC, GeorgeKuzora requested changes
Оставил комментарии по коду.

2023-04-30 13:58 UTC, GeorgeKuzora commented on src/parsers/scraper_trud_vsem.py
> +def check_connection(response: Any) -> bool:
Эта функция нигде не используется.

2023-04-30 13:58 UTC, GeorgeKuzora commented on src/parsers/scraper_trud_vsem.py
> +        return [False]
Если хочешь вернуть флаг что данные не найдены то лучше вернуть пустой лист. Лист с одним элементом False будет интерпретироваться как True, так как он не пустой.

2023-04-30 13:58 UTC, GeorgeKuzora commented on src/parsers/scraper_trud_vsem.py
> +    response = make_response(url)
Тут нет проверки что получен правильный ответ.

2023-04-30 13:58 UTC, GeorgeKuzora commented on src/parsers/scraper_trud_vsem.py
> +    try:
Не лучше ли проверять по каждой вакансии отдельно, иметь ли она необходимые данные?
В этой реализации мы ничего не получим даже если лишь одна вакансия выдаст ошибку.

2023-04-30 13:58 UTC, GeorgeKuzora commented on src/parsers/scraper_trud_vsem.py
> +print(search_vacancy(create_link(BASE_URL, ("Frontend", "Москва"))))
Это нужно убрать под `if __name__ == "__main__":`

Иначе это будет выполняться при импорте.

2023-04-30 13:58 UTC, GeorgeKuzora commented on src/parsers/scraper_trud_vsem.py
> +from typing import Any
Лучше типы определять более конкретно.

2023-05-02 16:45 UTC, Kustovweb commented on src/parsers/scraper_trud_vsem.py
> +def check_connection(response: Any) -> bool:
исправил

2023-05-02 16:45 UTC, Kustovweb commented on src/parsers/scraper_trud_vsem.py
> +        return [False]
исправил

2023-05-02 16:54 UTC, Kustovweb commented on src/parsers/scraper_trud_vsem.py
> +from typing import Any
исправил

2023-05-02 16:56 UTC, Kustovweb commented on src/parsers/scraper_trud_vsem.py
> +print(search_vacancy(create_link(BASE_URL, ("Frontend", "Москва"))))
определил функцию main() и в нее убрал вызовы, main() вызвал в if __name__ == "__main__":

2023-05-03 13:43 UTC, Kustovweb commented on src/parsers/scraper_trud_vsem.py
> +from typing import Any
ок

2023-05-03 15:55 UTC, GeorgeKuzora approved these changes
Не нужно перемещать крупные блоки кода и одновременно вносить мелкие изменения в одном коммите. Становиться непонятно где и какие изменения в коде были действительно внесены.

2023-05-03 15:58 UTC, merged