Hh parser
GeorgeKuzora/tg_bot_job_search pull request #5
Opened 2023-04-30 08:05 UTC by LushnikovSR

Модуль hh_parser.py - это программа Паук для парсинга сайта https://hh.ru (далее - сервер).
Задача программы извлекать данные о размещенных на сайте вакансиях по запросу пользователя.
Программа работает по следующему алгоритму: 
1. На сервер передаётся GET запрос с указанными поисковыми данными.
2. С сервера возвращается ресурсный код страницы со списком вакансий и общим количеством страниц содержащее результаты поиска.
3. Собирает все ссылки на карточки вакансий из результатов поиска размещенных на странице.
4. Заходит на каждую карточку вакансии и извлекает из неё список картежей целевых данных.
5. Повторяет пункты 3 и 4 проходя по всем страницам сформированных в пункте 2 результатов поиска.
6. Возвращает из модуля список с картежами содержащий целевые данные для вакансий со всех страниц.

Примечание: в ходе тестирования было выявлено что парсер выдаёт примерно в два раза меньше данных чем должен, это связано с динамической подгрузкой данных на страниц с результатами поиска. В ответе сервера содержится 20 вакансий на страницу с результатами поиска, динамически подгружается еще 30, суммарно 50. При этом общее количество страниц в ответе сервера определяется из расчёта 50 вакансий на страницу. 
В качестве решения проблемы возможно, при формировании программой поискового запроса, передать на сервер информацию о необходимости вывода результатов поиска в формате 20 вакансий на страницу. Для данного решения потребуется применение библиотеки selenium, так как данное условие поиска настраивается через GUI.

2023-04-30 13:56 UTC, GeorgeKuzora requested changes
Оставил комментарии по коду.
В целом лучше располагать функции и методы сверху вниз, от функций высокого уровня к функциям расскрывающим подробности низкого уровня.
Если в функции вызываются другие функции, то вызываемые функции лучше располагать ниже функции в которой они вызываются.

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +# from webdriver_manager.chrome import ChromeDriverManager
Пока эти библиотеки не используются лучше удалить их из файла.
Можешь создать отдельную ветку у себя в локальном репо, где бы ты постепенно внедрял эти закомментированные библиотеки. Когда функционал этих библиотек будет использоваться, то тогда можно и добавить их в main через отдельный pull request

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +def get_links(link: str, in_params: dict) -> str:
При yield возвращается генератор а не строка. Поэтому нужно поменять type hint на generator

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +def get_server_response(link: str, in_params: dict = None) -> requests.Response:
Для атрибута in_params указан тип dict а приваивание по умолчанию None. None имеет тип None, поэтому программа проверки кода ругается на несоответсвие типов. Нужно поменять на пустой словарь.

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +    data = requests.get(
Не совсем понятно по названию переменной что это за данные. Может лучше переименовать в response_data или просто response к примеру?

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +        return page_count
В хинте для метода ты указал что возвращаемое значение `str`, но по факту функция возвращает тип `int`. Нужно определить что именно нужно получать.

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +        for page in range(FIRST_PAGE, page_count + 1):
В хинте для функции `get_number_pages` указано что возвращаемое значение это `str`. Здесь ты прибавляешь `str` к `int`

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +def get_vacancy_ref(soup: bs) -> str: # как правильно указать возвращаемое значение?
Функция генератор возвращает тип Generator

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +def get_vacancys_data(keyward: str, region: str) -> list:
Опечатка в keyword и vacancies

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +def get_vacancy(link: str) -> tuple[str, str]:
Получается по факту ты возвращаешь не кортеж строк, а кортеж кортежей. Плюс насколько я понимаю, если указвать `str, str` это соответсвует именно двум вхождениям строк. В реальности возвращается пять элементов.

2023-04-30 13:56 UTC, GeorgeKuzora commented on src/parsers/hh_crawler.py
> +        return []
В хинте ты обозначил что возвращаешь кортеж, но здесь решил вернуть список.

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +def get_links(link: str, in_params: dict) -> str:
Сразу не разобрался потому что у меня Python 3.9.6 и похоже collections.abc в этой версии еще не поддерживает синтаксис аннотации. Поэтому пришлось подключить модуль typing и импортировать из него недостающие типы аннотаций абстрактных базовых классов.
Исправил.

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +        for page in range(FIRST_PAGE, page_count + 1):
Исправил hint для функции get_number_pages на int так что теперь в этой функции типы слагаемых одинаковые.

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +def get_vacancy_ref(soup: bs) -> str: # как правильно указать возвращаемое значение?
Исправил

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +        return page_count
Нужно получить int исправил hint

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +def get_server_response(link: str, in_params: dict = None) -> requests.Response:
Исправил, убрал значение по умолчанию

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +    data = requests.get(
Исправил

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +def get_vacancy(link: str) -> tuple[str, str]:
Исправил

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +        return []
Это исправил

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +def get_vacancys_data(keyward: str, region: str) -> list:
Это исправил.

2023-04-30 16:56 UTC, LushnikovSR commented on src/parsers/hh_crawler.py
> +# from webdriver_manager.chrome import ChromeDriverManager
С этим придётся повозиться так как мне нужно разбираться как пересоздать виртуальное окружение, либо в ручную убирать всё лишнее но боюсь ошибиться с комплектностью папок и связями, думаю за завтра разберусь.

2023-05-03 05:05 UTC, GeorgeKuzora approved these changes
Хорошо. Но в следующий раз, если делаешь перемещения больших кусков кода внутри файла и одновременно небольшие изменения в отдельных функциях, постарайся разделить эти два действия по разным коммитам. А то не слишком хорошо видно были ли изменения в перемещенном коде.

2023-05-03 05:08 UTC, merged